import type { FoodItem } from "./combo-datasets";

/**
 * Precios en CUP (pesos cubanos) por nombre de item.
 * Principales: 150-300, Acompañamientos: 50-150, Bebidas: 50-120, Postres: 80-180
 */
const priceMap: Record<string, number> = {
  // === PRINCIPALES ===
  "Wrap de pollo": 200,
  "Tostada de aguacate": 180,
  "Burrito de carne": 250,
  "Sándwich club": 220,
  "Bowl de pollo teriyaki": 250,
  "Panini de pavo": 200,
  "Ensalada César con pollo": 220,
  "Hamburguesa de res": 250,
  "Sopa de tomate": 150,
  "Quesadilla": 170,
  "Pasta alfredo": 200,
  "Sándwich de atún": 180,
  "Crepa de jamón y queso": 190,
  "Bowl de arroz con verduras": 180,
  "Taco de frijoles": 150,
  "Ensalada caprese": 170,
  "Pizza margarita": 220,
  "Tacos al pastor": 200,
  "Hamburguesa clásica": 230,
  "Wrap mediterráneo": 210,
  "Pollo empanizado": 220,
  "Sushi variado": 280,
  "Hot dog": 150,
  "Pasta pesto": 200,
  "Doble hamburguesa": 300,
  "Burrito XL": 280,
  "Milanesa con papas": 270,
  "Plato combinado": 280,
  "Torta de jamón": 200,
  "Pollo rostizado": 250,
  "Enchiladas verdes": 220,
  "Pizza familiar (2 rebanadas)": 250,
  "Sopa de pollo": 170,
  "Mac & Cheese": 190,
  "Grilled cheese": 160,
  "Crema de champiñones": 170,
  "Caldo de res": 200,
  "Molletes": 160,
  "Lasaña": 230,
  "Tamales": 180,

  // === ACOMPAÑAMIENTOS ===
  "Ensalada de quinoa": 120,
  "Fruta picada": 80,
  "Papas al horno": 100,
  "Mix de frutos secos": 90,
  "Edamame": 100,
  "Zanahoria con hummus": 90,
  "Pan integral": 60,
  "Ensalada mixta": 80,
  "Pan artesanal": 70,
  "Guacamole": 100,
  "Palitos de pan": 60,
  "Chips de plátano": 70,
  "Fruta de temporada": 80,
  "Sopa miso": 110,
  "Elote": 70,
  "Focaccia": 80,
  "Ensalada colorida": 90,
  "Nachos con queso": 120,
  "Papas fritas": 100,
  "Hummus con pita": 100,
  "Puré de papa": 80,
  "Aros de cebolla": 100,
  "Bruschetta": 90,
  "Papas fritas grandes": 120,
  "Nachos con todo": 140,
  "Sopa de fideos": 90,
  "Pan de ajo": 70,
  "Esquites": 80,
  "Arroz con frijoles": 100,
  "Frijoles refritos": 70,
  "Alitas BBQ": 150,
  "Pan recién horneado": 60,
  "Crostini": 70,
  "Arroz blanco": 60,
  "Plátano frito": 70,
  "Ensalada tibia": 90,
  "Frijoles de olla": 80,

  // === BEBIDAS ===
  "Jugo verde": 100,
  "Café americano": 80,
  "Smoothie de mango": 110,
  "Agua mineral": 50,
  "Té verde": 70,
  "Jugo de naranja": 90,
  "Agua de coco": 100,
  "Batido de proteína": 120,
  "Té de manzanilla": 60,
  "Limonada natural": 80,
  "Refresco": 70,
  "Agua con pepino": 60,
  "Café con leche": 90,
  "Té matcha": 100,
  "Horchata": 80,
  "Smoothie de fresa": 110,
  "Limonada rosa": 90,
  "Agua de jamaica": 80,
  "Milkshake de fresa": 120,
  "Jugo de piña": 90,
  "Jugo de manzana": 80,
  "Té de frutas": 70,
  "Refresco de uva": 70,
  "Agua mineral con limón": 60,
  "Refresco grande": 90,
  "Horchata grande": 100,
  "Agua de horchata": 80,
  "Jugo natural": 90,
  "Café con leche grande": 110,
  "Limonada": 80,
  "Agua fresca de tamarindo": 80,
  "Chocolate caliente": 100,
  "Leche con canela": 80,
  "Té chai": 80,
  "Café latte": 100,
  "Agua de limón tibia": 50,
  "Atole": 80,
  "Vino caliente (sin alcohol)": 90,
  "Champurrado": 90,

  // === POSTRES ===
  "Barrita energética": 80,
  "Plátano": 50,
  "Yogur con granola": 100,
  "Galleta de avena": 80,
  "Brownie": 100,
  "Helado de vainilla": 90,
  "Churros": 100,
  "Flan": 110,
  "Paleta de hielo": 60,
  "Brownie doble chocolate": 120,
  "Pastel de chocolate": 150,
  "Gelatina": 60,
  "Galletas de chocolate": 90,
  "Muffin de arándano": 100,
  "Arroz con leche": 80,
  "Helado": 90,
};

export function getItemPrice(itemName: string): number {
  return priceMap[itemName] ?? 0;
}

export function getComboTotal(items: FoodItem[]): number {
  return items.reduce((sum, item) => sum + getItemPrice(item.name), 0);
}
